# Generated by Django 4.2.7 on 2023-11-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.uuidmodel')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('color', models.CharField(db_column='color', max_length=7)),
            ],
            options={
                'db_table': 'categories',
            },
            bases=('common.uuidmodel',),
        ),
    ]
